### PR TITLE
allow `.yml` files as components

### PR DESCRIPTION
**Pull request by andrew-hillier**
I suspect that this will resolve https://github.com/dapr/dashboard/issues/195

### CODE REVIEW

**Review by toneill818 — APPROVED** [review]

**Review by toneill818 — APPROVED** [review]

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for this contribution!

**Comment by yaron2** [comment]
@andrew-hillier please check why build tests are failing

**Comment by yaron2** [comment]
@andrew-hillier thanks, we've now upgraded to Go 1.21. if you can resolve the conflicts that'd be great, and we can then merge

**Comment by andrew-hillier** [comment]
I'll revert the latest commit, as we can use `slices` from the standard lib too

**Comment by andrew-hillier** [comment]
@yaron2, had a little trouble with the DCO, but that should be ready to build now.

**Pull request merged**
