### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by l0ll098**
Hi everyone,
I've just updated every dependencies of this project since some had some security issues as reported by `npm audit` and some others (Angular) were using a no longer supported version, as described in the [documentation](https://angular.io/guide/releases#support-policy-and-schedule).

This was the output of the audit command: 
```log
found 419 vulnerabilities (117 moderate, 301 high, 1 critical) in 1800 scanned packages
run `npm audit fix` to fix 388 of them.
29 vulnerabilities require semver-major dependency updates.
2 vulnerabilities require manual review. See the full report for details. 
```

So, here's a list of notable changes:
 - Now Angular 12.2 is being used (in place of Angular 9.1)
 - Due to this change, Angular now requires TypeScript 4.2
 - IE9, IE10, and IE mobile are no longer supported (since Angular 11)
 - ❗ Support for IE11 has been deprected since Angular 12.0, as described in [RFC for IE11 removal](https://github.com/angular/angular/issues/41840)
 - Enabled [Ivy](https://angular.io/guide/ivy) since View Engine as been deprecated starting from Angular 12, as described [here](https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49)
 - Enabled Angular's [Strict mode](https://angular.io/guide/strict-mode). This should help to reduce runtime errors by identifying some potential pitfalls at compile time
 - 🎉Starting the web UI while developing is now faster

Another benefit of this upgrade is that you can now use the [Angular Chrome extension](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh). It is not complete as those available, for example, for VueJS, but at least it's something 

This PR makes #157 #156 #155 #154 #153 #152 #146 #144 #142 #141 #139 #132 #127 redundant and obsolete since those changes have already been incorporated in this pull request.

In case you have any questions/suggestions/doubts (or whatever), feel free to ping me :)

### CODE REVIEW

**Comment by artursouza** [comment]
@l0ll098 Thanks a lot for this contribution. I will validate it and add it to 0.8.

**Comment by artursouza** [comment]
BTW, can you resolve conflicts?

**Comment by artursouza** [comment]
LGTM. Please, resolve conflicts.

**Comment by l0ll098** [comment]
@artursouza I made those changes so now you should be able to merge

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
@l0ll098 Are you interested in becoming an approver and, later on, a maintainer for the Dapr dashboard?

**Comment by l0ll098** [comment]
@artursouza Of course! It would be amazing 💯

**Pull request merged**
