### PR TITLE
feat: upgrade to go 1.21 and bump deps

### PR DESCRIPTION
**Pull request by toneill818**
Upgrade to go 1.21 and bump dependencies

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
@toneill818 can you please check why the build is failing?

**Comment by yaron2** [comment]
Ping @toneill818

**Comment by toneill818** [comment]
@yaron2 Builds seem to be failing due to an old node version. Is it okay if I modify the node version for the runners in this PR?
> The Angular CLI requires a minimum Node.js version of v18.13.

**Comment by yaron2** [comment]
> @yaron2 Builds seem to be failing due to an old node version. Is it okay if I modify the node version for the runners in this PR?
> 
> > The Angular CLI requires a minimum Node.js version of v18.13.

Sure

**Comment by toneill818** [comment]
> > @yaron2 Builds seem to be failing due to an old node version. Is it okay if I modify the node version for the runners in this PR?
> > > The Angular CLI requires a minimum Node.js version of v18.13.
> 
> Sure

Should be fixed

**Comment by yaron2** [comment]
> > > @yaron2 Builds seem to be failing due to an old node version. Is it okay if I modify the node version for the runners in this PR?
> > > > The Angular CLI requires a minimum Node.js version of v18.13.
> > 
> > 
> > Sure
> 
> Should be fixed

Thanks!

**Pull request merged**
